### ISSUE TITLE
Wire Shortcuts Integration

### ISSUE THREAD

**Issue by Zehir** [oorzkws/factorio-customcircuitcolors#1]
Hello,

As we talk in this [issue](https://github.com/daydev/FactorioWireShortcuts/issues/6) is it's possible to have an integration with the other mod so the icon match the color picked in the wire selected in the mod ?

https://mods.factorio.com/mod/WireShortcuts

**Comment by oorzkws** [comment]
Sure, let me see what I can do.

**Comment by oorzkws** [comment]
Phew, that was surprisingly in-depth. It's now fixed and I'll upload to the mod portal shortly.
