### ISSUE TITLE
Incompatibility with mod Thicker Power Wires

### ISSUE THREAD

**Issue by Zehir** [oorzkws/factorio-customcircuitcolors#2]
Hello,

Just wanted to let you know that there is an issue with the [this mod](https://mods.factorio.com/mod/ThickerLines).

For some reason the colors get changed, see images below:
Without Thicker Power Wires
![image](https://user-images.githubusercontent.com/845225/232208603-dc43bda3-8b2d-4905-92ad-d7c4be9ed102.png)
With Thicker Power Wires (with same colors as above)
![image](https://user-images.githubusercontent.com/845225/232208623-776104b3-4e11-41bf-9813-7a517c2d9d9a.png)
With Thicker Power Wires (with differents colors as above)
![image](https://user-images.githubusercontent.com/845225/232208654-6cdd6d28-21dc-4655-af93-85f3fe66c0f2.png)

It's look like this mod keep changing the color but they got messed up by Thicker Power Wires mod.

I don't know if this can be fixed

**Comment by oorzkws** [comment]
Thanks for the report, it's now fixed. I'll be uploading to the portal shortly.

**Comment by oorzkws** [comment]
Ah and P.S. @lachlanmcdonald I've used your graphics for this compatibility patch, it's just color shifted. You are credited [here](https://github.com/oorzkws/factorio-customcircuitcolors/blob/163d6a995cac442322e3dbcc78e3fd25663ef40d/CREDITS#L2) - please let me know if you would prefer it elsewhere.

**Comment by lachlanmcdonald** [comment]
This is fine, thanks for the notice @oorzkws.

**Comment by Zehir** [comment]
Thanks both of you
